/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.UserRegistration;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import Business.Organization.Organization.Type;
import Business.Role.Farmer;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.UserRegistrationRequest;
import Business.WorkQueue.WorkQueue;
import UI.MainJFrame;
import java.awt.CardLayout;
import java.awt.PopupMenu;
import javax.swing.JOptionPane;
import javax.swing.JPanel;


/**
 *
 * @author sagar
 */
public class PanelUserRegistration extends javax.swing.JPanel {

    private EcoSystem system;
    private boolean flag = false;
    JPanel userProcessContainer;
    
    public PanelUserRegistration(JPanel userProcessContainer, EcoSystem system) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.system = system;
        fillCmbOrganization();
        fillCmbStateNetwork();
    }
    
    public void fillCmbOrganization()
    {
        cmbOrganization.addItem(Organization.Type.Farmer.getValue());
        cmbOrganization.addItem(Organization.Type.FarmingShopOwner.getValue());
        cmbOrganization.addItem(Organization.Type.Transporter.getValue());
        cmbOrganization.addItem(Organization.Type.BigMarket.getValue());
        cmbOrganization.addItem(Organization.Type.Company.getValue());
        cmbOrganization.addItem(Organization.Type.NGO.getValue());
        
        String orgType = cmbOrganization.getSelectedItem().toString();
        String Role = "";
        
        if(orgType.equals("Farmer Organization"))
            Role = "Farmer";
        else if(orgType.equals("ShopOwner Organization"))
            Role = "Shop Owner";
        else if(orgType.equals("Transporter Organization"))
            Role = "Transporter";
        else if(orgType.equals("BigMarket Organization"))
            Role = "Big Market Manager";
        else if(orgType.equals("Company Organization"))
            Role = "Company Manager";
        else if(orgType.equals("NGO Organization"))
            Role = "NGO Officer";
        
        lblDisplayRole.setText("Role : " + Role);
    }
    
    public void fillCmbStateNetwork()
    {
        cmbStateNetwork.removeAllItems();
        for (Network network : system.getNetworkList()) {
            cmbStateNetwork.addItem(network.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegister = new javax.swing.JButton();
        lblState = new javax.swing.JLabel();
        cmbStateNetwork = new javax.swing.JComboBox<>();
        lblDisplayRole = new javax.swing.JLabel();
        cmbOrganization = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblOrganization = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        lblPassword = new javax.swing.JLabel();
        txtEmailId = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        txtCity = new javax.swing.JTextField();
        lblContactNo = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblEmailId = new javax.swing.JLabel();
        lblCity = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRegister.setText("REGISTER");
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 551, 150, 35));

        lblState.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblState.setText("State:");
        add(lblState, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 499, 150, 30));

        cmbStateNetwork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(cmbStateNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 501, 200, 30));

        lblDisplayRole.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        add(lblDisplayRole, new org.netbeans.lib.awtextra.AbsoluteConstraints(801, 143, 188, 30));

        cmbOrganization.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOrganizationItemStateChanged(evt);
            }
        });
        add(cmbOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 143, 200, 30));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("NEW USER REGISTRATION");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(448, 50, -1, -1));

        txtUsername.setText("SagarK");
        add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 194, 200, 30));

        lblOrganization.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblOrganization.setText("Organization Type:");
        add(lblOrganization, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 141, 150, 30));

        txtName.setText("Sagar K");
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 296, 200, 30));

        lblUsername.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblUsername.setText("Username:");
        add(lblUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 193, 150, 30));

        txtContactNo.setText("1234567890");
        add(txtContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 347, 200, 30));

        lblPassword.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblPassword.setText("Password:");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 244, 150, 30));

        txtEmailId.setText("sk@gmail.com");
        add(txtEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 398, 200, 30));

        lblName.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblName.setText("Organization Name:");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 295, 150, 30));

        txtCity.setText("Boston");
        add(txtCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 449, 200, 30));

        lblContactNo.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblContactNo.setText("Contact No:");
        add(lblContactNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 346, 150, 30));

        txtPassword.setText("SagarK");
        add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 245, 200, 30));

        lblEmailId.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblEmailId.setText("Email Id:");
        add(lblEmailId, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 397, 150, 30));

        lblCity.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        lblCity.setText("City:");
        add(lblCity, new org.netbeans.lib.awtextra.AbsoluteConstraints(421, 448, 150, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed

        Network network = (Network) cmbStateNetwork.getSelectedItem();
        Type type = Type.valueOf(cmbOrganization.getSelectedItem().toString().split(" ")[0]);
        System.out.println("Check" + type);
        JOptionPane.showMessageDialog(null, "Check" + type);
        String emailAddress = txtEmailId.getText();
        String username = txtUsername.getText();
        String name = txtName.getText();
        String password = txtPassword.getText();
        String phone = txtContactNo.getText();
        String city = txtCity.getText();

        if (network == null || type == null || name.isEmpty() || username.isEmpty() || password.isEmpty() || emailAddress.isEmpty() || city.isEmpty() || phone.isEmpty())
        {
            JOptionPane.showMessageDialog(null, "All of the above the fields are required for registration!!", "Error!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (!system.checkValidPassword(password))
        return;
        if (!system.checkUniqueUser(username))
        return;
        if (!this.system.validateEmailFormat(emailAddress))
        return;
        if (!this.system.validatePhoneFormat(phone))
        return;

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount u : o.getUserAccountDirectory().getUserAccountList()) {
                        if (u.getEmail() != null) {
                            if (u.getEmail().toLowerCase().equals(emailAddress.toLowerCase())) {
                                JOptionPane.showMessageDialog(null, "Sorry! This Email Address already exists in our system", "Error!", JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                        }
                    }
                }
            }
        }

        for (Network n : system.getNetworkList()) {
            for (Enterprise e : n.getEnterpriseDirectory().getEnterpriseList()) {
                for (Organization o : e.getOrganizationDirectory().getOrganizationList()) {
                    for (UserAccount u : o.getUserAccountDirectory().getUserAccountList()) {
                        String phoneNo = String.valueOf(u.getPhoneNo());
                        if (phoneNo!= null) {
                            if (phoneNo.equals(phone)) {
                                JOptionPane.showMessageDialog(null, "Sorry! This Contact Number already exists in our system", "Error!", JOptionPane.ERROR_MESSAGE);
                                return;
                            }
                        }
                    }
                }
            }
        }

        if (Organization.Type.Farmer == type)
        {
            flag = true;
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
            {
                if (enterprise.getEnterpriseType() == Enterprise.EnterpriseType.FarmerCommunity)
                {
                    Organization org = enterprise.getOrganizationDirectory().createOrganization(type, name);
                    Employee emp = org.getEmployeeDirectory().createEmployee(name);
                    UserAccount ua1 = org.getUserAccountDirectory().createUserAccount(username, password, emp, new Farmer());
                    ua1.setEmail(emailAddress);
                    ua1.setPhoneNo(Long.parseLong(phone));
                    ua1.setCity(city);
                    String bodyMsg = "Hello " + username + ", \n Thank you for registering with us. Your account is activated. Happy Farming!";
                }
            }
        }
        else
        {
            UserRegistrationRequest registrationRequest = new UserRegistrationRequest();
            registrationRequest.setFullName(name);
            registrationRequest.setUserName(username);
            registrationRequest.setPassword(password);
            registrationRequest.setEmailId(emailAddress);
            registrationRequest.setNetwork(network);
            registrationRequest.setCity(city);
            registrationRequest.setOrgType(type);
            registrationRequest.setStatus("Requested");
            registrationRequest.setContactNo(phone);

            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList())
            {
                for (Organization org : enterprise.getOrganizationDirectory().getOrganizationList())
                {
                    if (org.getType() == type)
                    {
                        if (enterprise.getWorkQueue() == null)
                        {
                            enterprise.setWorkQueue(new WorkQueue());
                        }
                        flag = true;
                    }
                }
                if(flag)
                {
                    enterprise.getWorkQueue().getWorkRequestList().add(registrationRequest);
                }
            }
        }
        if (flag)
        {
            String bodyMsg = "Hello " + username + ", \n Thank you for registering with us. Your account will be activated within 48 hours. We will keep you posted here.";
            // We need to implement SMS and Email here
            JOptionPane.showMessageDialog(null, "You have been registered succesfully!");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Sorry! No such Organization is created by the enterprise");
        }
        txtName.setText("");
        txtUsername.setText("");
        txtPassword.setText("");
        txtEmailId.setText("");
        txtCity.setText("");
        txtContactNo.setText("");
        btnRegister.setEnabled(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void cmbOrganizationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOrganizationItemStateChanged
        // TODO add your handling code here:
        String orgType = cmbOrganization.getSelectedItem().toString();
        String Role = "";
        
        if(orgType.equals("Farmer Organization"))
            Role = "Farmer";
        else if(orgType.equals("ShopOwner Organization"))
            Role = "Shop Owner";
        else if(orgType.equals("Transporter Organization"))
            Role = "Transporter";
        else if(orgType.equals("BigMarket Organization"))
            Role = "Big Market Manager";
        else if(orgType.equals("Company Organization"))
            Role = "Company Manager";
        else if(orgType.equals("NGO Organization"))
            Role = "NGO Officer";

        lblDisplayRole.setText("Role : " + Role);
    }//GEN-LAST:event_cmbOrganizationItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegister;
    private javax.swing.JComboBox<String> cmbOrganization;
    private javax.swing.JComboBox<String> cmbStateNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCity;
    private javax.swing.JLabel lblContactNo;
    private javax.swing.JLabel lblDisplayRole;
    private javax.swing.JLabel lblEmailId;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblOrganization;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblState;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JTextField txtCity;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtEmailId;
    private javax.swing.JTextField txtName;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
