/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI.RoleFarmer;

import Business.EcoSystem;
import Business.Enterprise.Enterprise;
import Business.NGOHelp.NGOHelp;
import Business.ShopItems.ShopItems;
import Business.UserAccount.UserAccount;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sagar
 */
public class PanelRequestToNgo extends javax.swing.JPanel {

    /**
     * Creates new form PanelRequestToNgo
     */
    
    private JPanel userProcessContainer;
    private EcoSystem system;
    private UserAccount userAccount;
    private Enterprise enterprise;
    
    public PanelRequestToNgo(JPanel userProcess, EcoSystem system, Enterprise enterprise, UserAccount userAccount) {
        initComponents();
        this.userProcessContainer = userProcess;
        this.system = system;
        this.enterprise = enterprise;
        this.userAccount = userAccount;
    }
    
    public void populateTblReguestNgo()
    {
        DefaultTableModel model = (DefaultTableModel) tblReguestNgo.getModel();
        model.setRowCount(0);
        
        System.out.println(system.getNGOHelpDirectory().getNgoRequestList().size());
        
        for(NGOHelp ngoh : system.getNGOHelpDirectory().getNgoRequestList())
        {
            Object row[] = new Object[5];
            
            row[0] = ngoh.getUserAccount();
            row[1] = ngoh.getDamageReason();
            row[2] = ngoh.getDamageDetails();
            row[3] = ngoh.getAmount();
            row[4] = ngoh.getIncidentDate();
            
            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblDamageReason = new javax.swing.JLabel();
        lblDamageDetails = new javax.swing.JLabel();
        lblHelpAmount = new javax.swing.JLabel();
        lblIncidentDate = new javax.swing.JLabel();
        txtDamageReason = new javax.swing.JTextField();
        txtHelpAmount = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblReguestNgo = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnRefreshTable = new javax.swing.JButton();
        txtIncidentDate = new com.toedter.calendar.JDateChooser();
        txtDamageDetails = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("ASK FOR HELP TO NGO");

        lblDamageReason.setText("Damage Reason :");

        lblDamageDetails.setText("Damage Details :");

        lblHelpAmount.setText("Help Amount Needed :");

        lblIncidentDate.setText("Date of Incident :");

        txtDamageReason.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDamageReasonActionPerformed(evt);
            }
        });

        tblReguestNgo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Farmer", "Damage Reason", "Damage Details", "Amount Needed", "Date Of Incident"
            }
        ));
        jScrollPane2.setViewportView(tblReguestNgo);

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnRefreshTable.setText("Refresh Table");

        txtDamageDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDamageDetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 1140, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRefreshTable)
                    .addComponent(btnSave)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDamageReason, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDamageReason, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblDamageDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDamageDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 940, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblIncidentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtIncidentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(lblHelpAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(txtHelpAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lblTitle)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamageReason, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDamageReason, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDamageDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDamageDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHelpAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHelpAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblIncidentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtIncidentDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(btnSave)
                .addGap(41, 41, 41)
                .addComponent(btnRefreshTable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(115, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {lblDamageDetails, lblDamageReason, lblHelpAmount, lblIncidentDate, txtDamageDetails, txtDamageReason, txtHelpAmount, txtIncidentDate});

    }// </editor-fold>//GEN-END:initComponents

    private void txtDamageReasonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDamageReasonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDamageReasonActionPerformed

    private void txtDamageDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDamageDetailsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDamageDetailsActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        NGOHelp nh = new NGOHelp();
        nh.setDamageReason(txtDamageReason.getText());
        nh.setDamageDetails(txtDamageDetails.getText());
        nh.setAmount(txtHelpAmount.getText());
        nh.setIncidentDate(txtIncidentDate.getDate());
        nh.setUserAccount(userAccount);
        
        system.getNGOHelpDirectory().getNgoRequestList().add(nh);
        JOptionPane.showMessageDialog(null, "Request added successfully");
        
        txtDamageReason.setText("");
        txtDamageDetails.setText("");
        txtHelpAmount.setText("");
        
        populateTblReguestNgo();
    }//GEN-LAST:event_btnSaveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRefreshTable;
    private javax.swing.JButton btnSave;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblDamageDetails;
    private javax.swing.JLabel lblDamageReason;
    private javax.swing.JLabel lblHelpAmount;
    private javax.swing.JLabel lblIncidentDate;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTable tblReguestNgo;
    private javax.swing.JTextField txtDamageDetails;
    private javax.swing.JTextField txtDamageReason;
    private javax.swing.JTextField txtHelpAmount;
    private com.toedter.calendar.JDateChooser txtIncidentDate;
    // End of variables declaration//GEN-END:variables
}
